# Generated by Django 3.1.1 on 2020-09-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200921_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='photo',
        ),
    ]
