# Generated by Django 3.1 on 2020-08-29 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('old_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]))])),
                ('rank', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6.0)])),
                ('link', models.URLField()),
                ('photo', models.URLField()),
                ('date', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='api.destination')),
            ],
        ),
    ]
